name: multi-speciality-hospital infrastructure CI

on:
  push:
    branches: ["master", "development", "MSH*"]
  pull_request:
    branches: ["master", "development"]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0
      - name: change directory to terraform
        run: cd infrastructure/terraform
      - name: Terraform format
        run: terraform fmt -check
      - name: Terraform validate
        run: terraform validate
      - name: Terraform initialize
        run: terraform init
      - name: terraform plan
        run: terraform plan
      - name: Terraform apply
        run: terraform apply -auto-approve
