name: multi-speciality-hospital infrastructure CI

on:
  workflow_call:
  push:
    branches: ["master", "development", "MSH*"]
  pull_request:
    branches: ["master", "development"]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create S3 bucket for remote terraform state with bucket name in envrionment variable
        env:
          BUCKET_NAME: ${{ secrets.MSH_TERRAFORM_STATE_BUCKET }}
        run: |
          aws s3api create-bucket --bucket ${{ env.BUCKET_NAME }} --region us-east-1
      - name: Create DynamoDB table for terraform state locking if it does not exist
        env:
          LOCK_TABLE_NAME: msh-terraform-lock-table-dev
        run: |
          if ! aws dynamodb describe-table --table-name ${{ env.LOCK_TABLE_NAME }} > /dev/null 2>&1; then
            aws dynamodb create-table \
              --table-name ${{ env.LOCK_TABLE_NAME }} \
              --attribute-definitions AttributeName=LockID,AttributeType=S \
              --key-schema AttributeName=LockID,KeyType=HASH \
              --billing-mode PAY_PER_REQUEST
          fi
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0
      - name: Run terraform
        run: |
          cd infrastructure/terraform
          terraform init
          terraform fmt -check
          terraform validate
          terraform plan -lock=false
          terraform destroy -auto-approve
